# Ecommerce Analysis

#### In an environment where data drives strategic decision-making, this project demonstrates the use of Python to clean, analyze, and visualize client data—particularly in support of financial advisors. Utilizing powerful libraries such as pandas for data manipulation, NumPy for numerical operations, matplotlib and seaborn for visualization, and Plotly for interactive dashboard components, this project builds a foundation for producing clear, client-ready reports. Emphasis is placed on integrating and preparing data from multiple sources, ensuring accuracy, consistency, and insight-rich outputs that support real-time decision-making in a fast-growing business context.

## Table of contents

## Table of Contents
- [Libraries and data cleansing](#Libraries-and-data-cleansing)

### Libraries and data cleansing

In [3]:
import pandas as pd

In [27]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
maindf = pd.read_csv(r"C:\Users\user1\OneDrive\Documents\Ecommerce_Consumer_Behavior_Analysis_Data.csv")

In [9]:
maindf.head()

,Customer_ID,Age,Gender,Income_Level,Marital_Status,Education_Level,Occupation,Location,Purchase_Category,Purchase_Amount,...,Customer_Satisfaction,Engagement_with_Ads,Device_Used_for_Shopping,Payment_Method,Time_of_Purchase,Discount_Used,Customer_Loyalty_Program_Member,Purchase_Intent,Shipping_Preference,Time_to_Decision
0,37-611-6911,22,Female,Middle,Married,Bachelor's,Middle,Évry,Gardening & Outdoors,$333.80,...,7,NaN,Tablet,Credit Card,3/1/2024,True,False,Need-based,No Preference,2
1,29-392-9296,49,Male,High,Married,High School,High,Huocheng,Food & Beverages,$222.22,...,5,High,Tablet,PayPal,4/16/2024,True,False,Wants-based,Standard,6
2,84-649-5117,24,Female,Middle,Single,Master's,High,Huzhen,Office Supplies,$426.22,...,7,Low,Smartphone,Debit Card,3/15/2024,True,True,Impulsive,No Preference,3
3,48-980-6078,29,Female,Middle,Single,Master's,Middle,Wiwilí,Home Appliances,$101.31,...,1,NaN,Smartphone,Other,10/4/2024,True,True,Need-based,Express,10
4,91-170-9072,33,Female,Middle,Widowed,High School,Middle,Nara,Furniture,$211.70,...,10,NaN,Smartphone,Debit Card,1/30/2024,False,False,Wants-based,No Preference,4

In [10]:
maindf.shape

(1000, 28)

In [13]:
maindf.isnull().sum()

Customer_ID                                0
Age                                        0
Gender                                     0
Income_Level                               0
Marital_Status                             0
Education_Level                            0
Occupation                                 0
Location                                   0
Purchase_Category                          0
Purchase_Amount                            0
Frequency_of_Purchase                      0
Purchase_Channel                           0
Brand_Loyalty                              0
Product_Rating                             0
Time_Spent_on_Product_Research(hours)      0
Social_Media_Influence                   247
Discount_Sensitivity                       0
Return_Rate                                0
Customer_Satisfaction                      0
Engagement_with_Ads                      256
Device_Used_for_Shopping                   0
Payment_Method                             0
Time_of_Purchase                           0
Discount_Used                              0
Customer_Loyalty_Program_Member            0
Purchase_Intent                            0
Shipping_Preference                        0
Time_to_Decision                           0
dtype: int64

In [18]:
maindf['Social_Media_Influence'] = maindf['Social_Media_Influence'].fillna(maindf['Social_Media_Influence'].mode()[0])

In [20]:
maindf['Engagement_with_Ads'] = maindf['Engagement_with_Ads'].fillna(maindf['Engagement_with_Ads'].mode()[0])

In [22]:
maindf.duplicated().sum()

0

In [23]:
maindf.dtypes

Customer_ID                               object
Age                                        int64
Gender                                    object
Income_Level                              object
Marital_Status                            object
Education_Level                           object
Occupation                                object
Location                                  object
Purchase_Category                         object
Purchase_Amount                           object
Frequency_of_Purchase                      int64
Purchase_Channel                          object
Brand_Loyalty                              int64
Product_Rating                             int64
Time_Spent_on_Product_Research(hours)    float64
Social_Media_Influence                    object
Discount_Sensitivity                      object
Return_Rate                                int64
Customer_Satisfaction                      int64
Engagement_with_Ads                       object
Device_Used_for_Shopping                  object
Payment_Method                            object
Time_of_Purchase                          object
Discount_Used                               bool
Customer_Loyalty_Program_Member             bool
Purchase_Intent                           object
Shipping_Preference                       object
Time_to_Decision                           int64
dtype: object

In [24]:
maindf['Purchase_Amount'] = pd.to_numeric(maindf['Purchase_Amount'], errors='coerce')
maindf['Engagement_with_Ads'] = pd.to_numeric(maindf['Engagement_with_Ads'], errors='coerce')
maindf['Time_of_Purchase'] = pd.to_datetime(maindf['Time_of_Purchase'], errors='coerce')

In [25]:
maindf.describe(include='all')

,Customer_ID,Age,Gender,Income_Level,Marital_Status,Education_Level,Occupation,Location,Purchase_Category,Purchase_Amount,...,Customer_Satisfaction,Engagement_with_Ads,Device_Used_for_Shopping,Payment_Method,Time_of_Purchase,Discount_Used,Customer_Loyalty_Program_Member,Purchase_Intent,Shipping_Preference,Time_to_Decision
count,1000,1000.000000,1000,1000,1000,1000,1000,1000,1000,0.0,...,1000.000000,0.0,1000,1000,1000,1000,1000,1000,1000,1000.000000
unique,1000,NaN,8,2,4,3,2,969,24,NaN,...,NaN,NaN,3,5,NaN,2,2,4,3,NaN
top,37-611-6911,NaN,Female,High,Widowed,Bachelor's,High,Oslo,Electronics,NaN,...,NaN,NaN,Desktop,PayPal,NaN,True,False,Need-based,No Preference,NaN
freq,1,NaN,452,515,260,341,517,4,54,NaN,...,NaN,NaN,350,219,NaN,521,509,256,372,NaN
mean,NaN,34.304000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.399000,NaN,NaN,NaN,2024-06-29 06:31:40.800000,NaN,NaN,NaN,NaN,7.547000
min,NaN,18.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.000000,NaN,NaN,NaN,2024-01-01 00:00:00,NaN,NaN,NaN,NaN,1.000000
25%,NaN,26.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.000000,NaN,NaN,NaN,2024-04-04 00:00:00,NaN,NaN,NaN,NaN,4.000000
50%,NaN,34.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.000000,NaN,NaN,NaN,2024-06-30 00:00:00,NaN,NaN,NaN,NaN,8.000000
75%,NaN,42.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.000000,NaN,NaN,NaN,2024-09-19 00:00:00,NaN,NaN,NaN,NaN,11.000000
max,NaN,50.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.000000,NaN,NaN,NaN,2024-12-30 00:00:00,NaN,NaN,NaN,NaN,14.000000
std,NaN,9.353238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.868454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.035849

### Customer Segmentation Foundation

##### Profile who buys more
##### Understand when people shop
##### Identify potential drivers of purchase amount or intent

In [29]:
gender_group = maindf.groupby('Gender')['Purchase_Amount'].agg(['mean', 'median', 'count']).sort_values(by='mean', ascending=False)
print("Purchase by Gender:\n", gender_group)

Purchase by Gender:
              mean  median  count
Gender
Agender       NaN     NaN      0
Bigender      NaN     NaN      0
Female        NaN     NaN      0
Genderfluid   NaN     NaN      0
Genderqueer   NaN     NaN      0
Male          NaN     NaN      0
Non-binary    NaN     NaN      0
Polygender    NaN     NaN      0

In [30]:
maindf['Purchase_Amount'] = maindf['Purchase_Amount'].replace('[\$,]', '', regex=True)
maindf['Purchase_Amount'] = pd.to_numeric(maindf['Purchase_Amount'], errors='coerce')

In [31]:
print(maindf['Purchase_Amount'].isna().sum())

1000

In [33]:
print(maindf['Purchase_Amount'].unique()[:10])

[nan]

In [1]:
print('test')

test